### PR TITLE
add MongoDB, mongoose, new seed script, & change repo to remove one directory

### PR DESCRIPTION
**Pull request by keenanthomson**
PR includes:

- adding Mongoose module and associated db methods
- adding new seed script to populate mongo db
- removed a master 'reservation' folder that contained entire repo

Let me know if you have questions - thanks!

### CODE REVIEW

**Comment by willmainwaring** [comment]
Looking good! You completed your CRUDdy api for MySQL, but are you still working on Mongo?

**Comment by keenanthomson** [comment]
I wasn't planning to yet (per Learn) until I benchmark the two and pick a final one to move forward with. This was the requirements I saw: 
Screen Shot 2019-08-14 at 9 40 24 PM

**Comment by willmainwaring** [comment]
Got it, that makes sense.

**Comment by keenanthomson** [comment]
Thanks for the review Will! I'll merge it.

**Pull request merged**
